spring:
  elasticsearch:
    uris: http://localhost:9200
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///springboot_db?useSSL=false&serverTimezone=UTC
      username: root
      password: ganga
  cache:
    type: redis # 指定使用的缓存技术 默认是Simple可以不写
    # spring.cache.redis.xxx 是springboot 整合 redis 缓存用的配置
    redis:
      cache-null-values: true # 是否删除为null的key 默认值为true
      use-key-prefix: true    # 是否允许存储空值 默认值是true 一般都要为true 提高key不重复
      key-prefix: msg_        # 追加自定义前缀名  一般都要追加 提高key不重复
      time-to-live: 10s       # 10s 有效时长
  # spring.redis.xxx 是springboot 整合 redis 连接客户端用的配置
  redis:
    port: 6379
    host: localhost


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-prefix: tb_


server:
  port: 80
