server:
  port: 81

spring:
  kafka:
    bootstrap-servers: localhost:9092 # kafka 服务端地址及端口号
    consumer:
      group-id: order_msg # 指定一个消费者 组


  boot:
    admin:
      client:
        url: http://localhost:8080
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
