spring:
  redis:
    host: localhost
    port: 6379
    # client-type: lettuce # 设置实现技术 默认是lettuce
    client-type: jedis

    lettuce:
      pool: # lettuce 设置属性
        max-active: 16 # lettuce最大连接数量
    jedis:
      pool: # jedis 设置属性
        max-active: 16 # jedis最大连接数量
