server:
  port: 80

# 日志配置
spring:
  profiles:
    active: config04


---
spring:
  config:
    activate:
      on-profile: config01

  # 开启debug
debug: true

---
spring:
  config:
    activate:
      on-profile: config02

# 配置日志级别  推选使用方式
logging:
  level:
    root: warn
    # root是根目录及其以下的所有日志

---
spring:
  config:
    activate:
      on-profile: config03

# 配置指定包日志级别
logging:
  level:
    com.ganga.controller: trace
    # 刚刚指定的是root根目录下所有的 现在设置为com.ganga.controller包下的日志


---
spring:
  config:
    activate:
      on-profile: config04

# 分组配置配置日志级别  推选使用
logging:
  # 自定义设置分组 分组名: 包名
  group:
    ebank: com.ganga.controller,com.ganga.service,com.ganga.dao
    edao: com.ganga.dao
  # 分组名: 分组级别
  level:
    ebank: debug
    edao: trace
