# 配置SpringTask
spring:
  task:
    scheduling:
      # 配置线程前缀 一般用于调试
      thread-name-prefix: Test_task_
      # 线程最最大数量
      pool:
        size: 20
      shutdown:
        # 线程池关闭时等待所有任务完成
        await-termination: false
        # 调度线程关闭前最大等待时间，确保最后一定关闭
        await-termination-period: 10s
