# 配置端口号
server:
  port: 80 # 80 端口


# 配置数据源连接池
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///springboot_db?useSSL=false&serverTimezone=UTC
      username: root
      password: ganga

  # 配置监控服务器 url
  boot:
    admin:
      client:
        url: http://localhost:8080

# 配置要监听的信息
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true


# 配置mybatis-plus 相关配置
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_ # 设置表前缀
      id-type: auto # 设置id为数据库自增

  configuration: # 设置日志 输出在控制台上
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# info信息
info:
  appName: brand_ssm


