# 配置文件分级：
# 2. 第二级：项目经理使用环境配置
# --低级有的 高级没有 会自动继承
# --低级有的 高级也有 会覆盖低级


# 配置端口号
server:
  port: 82 # test 82 端口


# 配置数据源连接池
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///springboot_db?useSSL=false&serverTimezone=UTC
      username: root
      password: ganga
  main:
    banner-mode: console
  banner:
    image:
      location: logo.png